engines:
  phpcodesniffer:
    enabled: true
    checks:
      Squiz ControlStructures ControlSignature SpaceAfterKeyword:
        enabled: false
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
  - "tests/_files/*"
