language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

addons:
  - code_climate

after_script:
  - vendor/bin/test-reporter
