language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - composer install --prefer-source --no-interaction

script:
  - phpunit

after_success:
  - vendor/bin/test-reporter

addons:
  - code_climate

matrix:
  allow_failures:
    - php: hhvm
