language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

addons:
    code_climate:
        repo_token: b6cee06aa4389089a3ecd77fb0264b2b00c0f3b50576e87eaf8b9091a93d1e4d
